version: "3"

services:
  micro-api:
    container_name: micro-api
    image: micro-api
    build: .
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - FLASK_APP=/home/micro-api/autoapp.py
    volumes:
      - ${BASE_DIR}:/home/micro-api
    ports:
      - 5000:5000
    entrypoint: flask run --host=0.0.0.0

networks:
  default:
    external:
      name: lipotes-network
